theme: jekyll-theme-minimal
message: Welcome to the blog of Rob Weston
author: Rob Weston
title: Rob Weston
mugshot: /assets/images/mugshot.jpg
social:
    - id: 'robw@robots.ox.ac.uk'
      href: 'mailto:'
      title: 'Email'
      fa-icon: 'fas fa-envelope'
#    - id: ''
#      href: /cv.html
#      title: cv
#      fa-icon: 'fas fa-book'
    - id: robw4
      href: https://www.github.com/
      title: GitHub
      fa-icon: 'fab fa-github'
    - id: rob-weston-a1289a177
      href: https://www.linkedin.com/in/
      title: LinkedIn
      fa-icon: 'fab fa-linkedin'
    - id: HODw_M0AAAAJ&hl=en
      href: https://scholar.google.com/citations?
      title: Scholar
      fa-icon: 'ai ai-google-scholar'
#    - id: robwrobots
#      href: https://twitter.com/
#      title: Twitter
#      fa-icon: 'fab fa-twitter'
    - id: athletes/5902010
      href: https://www.strava.com/
      title: 'strava'
      fa-icon: "fab fa-strava"
page_width: 900px
numbered: false
markdown: kramdown
kramdown:
  math_engine: mathjax
