theme: jekyll-theme-minimal
message: Welcome to the blog of Rob Weston
author: robw
social:
    - id: 'robw@robots.ox.ac.uk'
      href: 'mailto:'
      title: 'Email'
      fa-icon: 'fa-envelope-square'
    - id: 'robwrobots'
      href: 'https://www.twitter.com/'
      title: 'Twitter'
      fa-icon: 'fa-twitter-square'
    - id: robw4
      href: 'https://github.com/'
      tite: GitHub
      fa-icon: 'fa-github-square'
page_width: 800px
markdown: kramdown
kramdown:
  math_engine: mathjax