theme: jekyll-theme-minimal
message: Welcome to the blog of Rob Weston
author: Rob Weston
title: Rob Weston
mugshot: /assets/images/mugshot.jpg
social:
    - id: 'robw@robots.ox.ac.uk'
      href: 'mailto:'
      title: 'Email'
      fa-icon: 'fa-envelope-square'
#    - id: 'robwrobots'
#      href: 'https://www.twitter.com/'
#      title: 'Twitter'
#      fa-icon: 'fa-twitter-square'
    - id: robw4
      href: https://www.github.com
      title: GitHub
      fa-icon: 'fa-github-square'
    - id: rob-weston-a1289a177
      href: https://www.linkedin.com/in/
      tite: LinkedIn
      fa-icon: 'fa-linkedin-square'
page_width: 900px
numbered: true
markdown: kramdown
kramdown:
  math_engine: mathjax
